# Generated by Django 5.1.4 on 2025-01-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wishlistitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='priority',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='size',
            field=models.CharField(choices=[('Stocking', 'Stocking'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
    ]
