# Generated by Django 5.1.4 on 2025-01-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wishlistitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='link',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
