# Generated by Django 5.1.4 on 2025-01-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_wishlistitem_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['priority', '-created_at']},
        ),
    ]
